/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      maxWidth: { layout: "1440px" },
      spacing: { 18: "4.5rem", 22: "5.5rem" },
      colors: {
        bg: "#ffffff",
        surface: "#ffffff",
        panel: "#ffffff",
        card: "#ffffff",
        navy: "#ffffff",
        border: "rgba(10,10,10,0.12)",
        accent: "#0a0a0a",
        eligible: "#0d7a3e",
        deny: "#c41e1e",
        review: "#b35900",
        txt: "#0a0a0a",
        "txt-2": "#2a2a2a",
        muted: "#5c5c5c",
        frost: "#3a3a3a",
        line: "rgba(10,10,10,0.12)",
      },
      fontFamily: {
        sans: ["DM Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["Syne", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["IBM Plex Mono", "ui-monospace", "monospace"],
      },
      borderRadius: { "2xl": "0", "3xl": "0" },
      boxShadow: {
        hud: "none",
        glass: "none",
        "accent-glow": "8px 8px 0 rgba(10,10,10,0.08)",
        "accent-glow-sm": "4px 4px 0 rgba(10,10,10,0.06)",
      },
      animation: {
        "app-enter": "appEnter 0.55s cubic-bezier(0.22,1,0.36,1) forwards",
        "step-enter": "stepEnter 0.32s cubic-bezier(0.22,1,0.36,1) forwards",
        "fade-slide": "fadeIn 0.32s ease-out forwards",
        drawer: "drawerIn 0.28s cubic-bezier(0.25,0.46,0.45,0.94) forwards",
        "status-pulse": "statusPulse 2.4s ease-in-out infinite",
        "splash-progress": "splashProgress 1.8s ease-out forwards",
        "overlay-exit": "overlayExit 0.4s ease-out forwards",
      },
      keyframes: {
        appEnter: { "0%": { opacity: "0", transform: "translateY(12px)" }, "100%": { opacity: "1", transform: "none" } },
        stepEnter: { "0%": { opacity: "0", transform: "translateY(8px)" }, "100%": { opacity: "1", transform: "none" } },
        fadeIn: { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        drawerIn: { "0%": { transform: "translateX(100%)" }, "100%": { transform: "translateX(0)" } },
        statusPulse: { "0%,100%": { opacity: "0.5", transform: "scale(1)" }, "50%": { opacity: "1", transform: "scale(1.2)" } },
        splashProgress: { "0%": { transform: "scaleX(0)" }, "100%": { transform: "scaleX(1)" } },
        overlayExit: { "0%": { opacity: "1" }, "100%": { opacity: "0" } },
      },
      transitionDuration: { "160": "160ms" },
    },
  },
  plugins: [],
};
